name: sohbetapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.14.1+3
  crypto: ^2.1.5
  cupertino_icons: ^1.0.0
  background_app_bar: ^1.0.3
  firebase_auth: ^0.18.1+2
  random_color: ^1.0.5
  story: ^0.4.0
  cached_network_image: ^2.5.1
  scroll_to_index: ^1.0.6
  youtube_explode_dart: ^1.8.0
  flutter_svg: ^0.19.0
  firebase_messaging: ^7.0.3
  shimmer: ^1.1.2
  bordered_text: ^1.0.1
  firebase_storage: ^4.0.1
  permission_handler: ^5.0.1+1
  theme_provider: ^0.4.0+1
  screenshot_callback: ^1.1.5
  percent_indicator: ^2.1.9
  device_apps: ^1.3.0
  image_editor: ^0.7.3
  giphy_get: ^1.0.0
  pie_chart: ^4.0.1
  get_it: ^5.0.1
  flutter_colorpicker: ^0.3.5
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  encrypt: ^4.1.0
  http: ^0.12.2
  image_picker: ^0.6.7+4
  emoji_picker: ^0.1.0
  linkwell: ^0.1.9
  url_launcher: ^5.7.10
  random_string: ^2.1.0
  flutter_keyboard_visibility: ^4.0.2
  path_provider: ^1.6.27
  font_awesome_flutter: ^8.11.0
  path: ^1.7.0
  camera: ^0.6.4+5
  flutter_contacts: ^0.0.7
  flutter_slidable: ^0.5.7
  sms_autofill: ^1.2.7
  geolocator: ^6.1.14
  google_map_location_picker: ^4.1.2+1
  filesize: ^1.0.4
  gx_file_picker: ^1.9.0+2
  pinput: ^0.2.6
  cool_alert: ^1.0.3
  provider: ^4.0.5
  image_gallery_saver: ^1.6.7
  webview_flutter: ^1.0.7
  rxdart: ^0.24.0
  grouped_list: ^3.7.1
  dio: ^3.0.10
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.16.0
  flutter_speed_dial: ^1.2.5
  auto_size_text: ^2.1.0
  contextualactionbar: ^2.1.0
  chewie: ^0.9.10
  flutter_launcher_icons: ^0.8.1
  video_player: ^0.10.9
  video_thumbnail: ^0.2.5+1
  clipboard: ^0.1.2+8
  open_file: ^3.0.3
  dotted_border: ^1.0.7
  google_maps_flutter: ^1.1.1
  agora_rtc_engine: ^3.2.1
  flutter_widget_from_html: ^0.5.2+1
  google_fonts: ^1.1.2
  flutter_snake_navigationbar: ^0.4.4

dependency_overrides:
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/svg/
    - assets/png/
    - assets/icon/
    - assets/gifs/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Omegle
      fonts:
        - asset: assets/fonts/omegle.ttf
    - family: 
      fonts:
        - asset: assets/fonts/TheStudentsTeacher-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
